kind: ConfigMap
metadata:
  name: topics-config
  namespace: kafka
apiVersion: v1
data:
  create-topics.sh: |-
    #!/bin/bash
    set -e
    set -x
    
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic virtual-users --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic find-me --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic tag-maker --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognizer-virtual-users --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic signin-log --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognizer-real-time --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic similarity --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognizer-batch --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognizer-best-effort --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognition-results --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognition-knn5-results --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognition-knn5ex-results --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognition-knn20-results --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic recognition-aws-results --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-locations --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic upload-requests --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic resize-requests --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic transformation-requests --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-web-images --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic picture-changed --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-picture --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic delete-file --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic picture-removed --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-video --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-video-web --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-signin-media --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic add-user-domain --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic picture-changed-signin --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic new-media-order --partitions 99 --replication- factor 3
    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --create --if-not-exists --topic analytics-queues-work --partitions 99 --replication- factor 3


    ./bin/kafka-topics.sh --zookeeper zookeeper.kafka.svc.cluster.local:2181 --list


