apiVersion: batch/v1
kind: Job
metadata:
  name: topics-create
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: topic-create
        image: solsson/kafka-cli@sha256:9fa3306e9f5d18283d10e01f7c115d8321eedc682f262aff784bd0126e1f2221
        command: ['/bin/bash', '/etc/kafka-configmap/create-topics.sh']
        volumeMounts:
        - name: configmap
          mountPath: /etc/kafka-configmap
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
      restartPolicy: Never
      volumes:
      - name: configmap
        configMap:
          name: topics-config
