apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: broker
          resources:
            requests:
              cpu: 2500m
              memory: 9Gi
            limits:
              cpu: 3000m
              memory: 9Gi