apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: zookeeper
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 1500m
              memory: 2Gi