apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: kafka
spec:
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: "kafka-pool"
      tolerations:
      - key: "gke-nodepool"
        operator: "Equal"
        value: "kafka-pool"
        effect: "NoSchedule"
